name: server_code_lab
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Code-lab server sample.
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  _discoveryapis_commons: ^0.1.0
  browser: ^0.10.0+2
  crypto: ^0.9.0
  http: ^0.11.1
  http_server: ^0.9.5+1
  logging_handlers: ^0.8.0
  rpc: ^0.5.0
  google_oauth2_client: ^0.2.2
  postgresql: "^0.3.1+1"
  bignum:
      git: git://github.com/Dartist/dart-bignum.git

dev_dependencies:
  test: "^0.12.3+8"